// Auto-generated edge routes — do not edit manually.
// Generated by: bun run nx build:edge

import { Elysia } from 'elysia'

import { Auth } from './pages/auth.ts'
import { Cache } from './pages/cache.ts'
import { Home } from './pages/index.ts'
import { Users } from './pages/users.ts'

const app = new Elysia()

// Health check
app.get('/health', () => new Response(JSON.stringify({
  status: 'ok',
  runtime: typeof Bun !== 'undefined' ? 'bun' : 'edge',
}), { headers: { 'content-type': 'application/json' }}))

// Routes
  app.get('/api/auth', async (ctx) => {
    const ctrl = new Auth()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.index()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.post('/api/auth', async (ctx) => {
    const ctrl = new Auth()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.create()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.delete('/api/auth/:id', async (ctx) => {
    const ctrl = new Auth()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.destroy(id)
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.get('/api/cache', async (ctx) => {
    const ctrl = new Cache()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.index()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.post('/api/cache', async (ctx) => {
    const ctrl = new Cache()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.create()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.delete('/api/cache/:id', async (ctx) => {
    const ctrl = new Cache()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.destroy(id)
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.get('/api', async (ctx) => {
    const ctrl = new Home()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.index()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.get('/api/users', async (ctx) => {
    const ctrl = new Users()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.index()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.get('/api/users/:id', async (ctx) => {
    const ctrl = new Users()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.show(id)
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.post('/api/users', async (ctx) => {
    const ctrl = new Users()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.create()
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.put('/api/users/:id', async (ctx) => {
    const ctrl = new Users()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.update(id)
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

  app.delete('/api/users/:id', async (ctx) => {
    const ctrl = new Users()
    ;(ctrl as any).ctx = ctx
    const id = ctx.params?.id ? Number(ctx.params.id) : undefined
    const result = await ctrl.destroy(id)
    if (result instanceof Response) return result
    return new Response(JSON.stringify(result ?? {}), {
      headers: { 'content-type': 'application/json' }
    })
  })

export default app
