// Auto-generated edge routes — do not edit manually.
// Generated by: bun run nx build:edge

import { Elysia } from 'elysia'

import { UnknownController } from './pages/hello.ts'

const app = new Elysia()

// Health check
app.get('/health', () => new Response(JSON.stringify({
  status: 'ok',
  runtime: typeof Bun !== 'undefined' ? 'bun' : 'edge',
}), { headers: { 'content-type': 'application/json' }}))

// Routes


export default app
